//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using System.Runtime.InteropServices;

public class BasicWorldStream : IWorldStreamSource
{
	public BasicWorldStream ()
	{
	}

	public List<ChunkObject> GetObjects(Bounds mapbounds)
	{
		int numberOfObjects = UnityEngine.Random.Range(0, 10000);
		
		List<ChunkObject> retEnum = new List<ChunkObject>(numberOfObjects);
		for (int i = 0; i < numberOfObjects; i++)
		{	
			// Get the position of the new object
			float xLocation = UnityEngine.Random.Range(mapbounds.min.x, mapbounds.max.x);
			float yLocation = UnityEngine.Random.Range(mapbounds.min.y, mapbounds.max.y);
			float zLocation = UnityEngine.Random.Range(mapbounds.min.z, mapbounds.max.z);

			ChunkObject newobject = new ChunkObject(){
				Position = new Vector3(xLocation, yLocation, zLocation), 
				Scale = Vector3.one, 
				Rotation = Quaternion.identity, 
				ChunkObjectType = "Asteroid"};

			retEnum.Add(newobject);
		}

		return retEnum;
	}
}


