//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public struct ChunkObject
{
	public Vector3 Position {get;set;}
	public Quaternion Rotation {get;set;}
	public Vector3 Scale {get;set;}
	public String ChunkObjectType {get;set;}
}


